name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out files
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build
